# Generated by Django 5.0.3 on 2024-05-03 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlepage",
            old_name="slug",
            new_name="subtilte",
        ),
        migrations.RenameField(
            model_name="blogpage",
            old_name="posted_by",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="blogpage",
            old_name="posted_on",
            new_name="publish_date",
        ),
        migrations.RenameField(
            model_name="blogpage",
            old_name="slug",
            new_name="subtilte",
        ),
    ]
